import SwiftUI

struct HistoryView: View {
    @EnvironmentObject private var store: POStore
    @EnvironmentObject private var authStore: AuthStore
    @State private var searchText = ""
    @State private var sort: HistorySort = .dateNewest
    @State private var statusFilter: POStatus?
    @State private var exportPayload: ExportPayload?

    private var hasReceipts: Bool {
        store.history.contains { !$0.receipts.isEmpty }
    }

    /// History filtered by the status filter and the search term (customer name or
    /// job number), then sorted.
    private var displayedHistory: [PurchaseOrder] {
        let query = searchText.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        let filtered = store.history.filter { po in
            let matchesStatus = statusFilter == nil || po.status == statusFilter
            let matchesQuery = query.isEmpty
                || po.customerName.lowercased().contains(query)
                || po.jobNumber.lowercased().contains(query)
            return matchesStatus && matchesQuery
        }
        return sort.sorted(filtered)
    }

    var body: some View {
        NavigationStack {
            Group {
                if store.history.isEmpty && !store.isLoadingHistory {
                    emptyState
                } else if displayedHistory.isEmpty {
                    noMatchesState
                } else {
                    List(displayedHistory) { po in
                        NavigationLink(value: po) {
                            VStack(alignment: .leading, spacing: 4) {
                                HStack {
                                    Text(po.poNumber)
                                        .font(.system(.body, design: .monospaced))
                                        .bold()
                                        .foregroundColor(Theme.accent)
                                    Spacer()
                                    statusMenu(for: po)
                                }
                                Text("\(po.customerName) · Job \(po.jobNumber)")
                                    .font(.subheadline)
                                    .foregroundColor(.secondary)
                                Text("By \(po.createdByName) · \(po.createdAt.formatted(date: .abbreviated, time: .shortened))")
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                            .padding(.vertical, 2)
                        }
                        .listRowBackground(Theme.panel)
                    }
                    .scrollContentBackground(.hidden)
                    .background(Theme.background)
                    .navigationDestination(for: PurchaseOrder.self) { po in
                        PODetailView(po: po)
                    }
                    .refreshable {
                        await store.loadHistory()
                    }
                }
            }
            .navigationTitle("HISTORY")
            .searchable(text: $searchText, prompt: "Customer or job number")
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button {
                        exportPayload = ExportPayload(urls: ReceiptExporter.exportURLs(forAll: store.history))
                    } label: {
                        Label("Export Receipts", systemImage: "square.and.arrow.up")
                    }
                    .disabled(!hasReceipts)
                }
                ToolbarItem(placement: .topBarTrailing) {
                    filterMenu
                }
                ToolbarItem(placement: .topBarTrailing) {
                    sortMenu
                }
            }
            .sheet(item: $exportPayload) { payload in
                ShareSheet(items: payload.urls)
            }
            .task {
                await store.loadHistory()
            }
        }
    }

    private var emptyState: some View {
        VStack(spacing: 12) {
            Image(systemName: "shippingbox")
                .font(.system(size: 40))
                .foregroundColor(Theme.steel)
            Text("No POs Yet")
                .font(.headline)
            Text("Purchase orders generated by you or your team will show up here.")
                .font(.subheadline)
                .foregroundColor(.secondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 32)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Theme.background)
    }

    private var noMatchesState: some View {
        VStack(spacing: 12) {
            Image(systemName: "magnifyingglass")
                .font(.system(size: 40))
                .foregroundColor(Theme.steel)
            Text("No Matches")
                .font(.headline)
            Text(noMatchesDescription)
                .font(.subheadline)
                .foregroundColor(.secondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 32)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Theme.background)
    }

    private var noMatchesDescription: String {
        let trimmed = searchText.trimmingCharacters(in: .whitespacesAndNewlines)
        switch (trimmed.isEmpty, statusFilter) {
        case (false, .some(let status)):
            return "No \(status.label) purchase orders match \"\(trimmed)\"."
        case (false, .none):
            return "No purchase orders match \"\(trimmed)\"."
        case (true, .some(let status)):
            return "No purchase orders are marked \(status.label)."
        case (true, .none):
            return "No purchase orders to show."
        }
    }

    private var filterMenu: some View {
        Menu {
            Picker("Filter by Status", selection: $statusFilter) {
                Label("All Statuses", systemImage: "line.3.horizontal.decrease")
                    .tag(POStatus?.none)
                ForEach(POStatus.allCases) { status in
                    Label(status.label, systemImage: status.systemImage)
                        .tag(POStatus?.some(status))
                }
            }
        } label: {
            Label("Filter", systemImage: statusFilter == nil
                ? "line.3.horizontal.decrease.circle"
                : "line.3.horizontal.decrease.circle.fill")
        }
    }

    private var sortMenu: some View {
        Menu {
            Picker("Sort", selection: $sort) {
                ForEach(HistorySort.allCases) { option in
                    Label(option.label, systemImage: option.systemImage).tag(option)
                }
            }
        } label: {
            Label("Sort", systemImage: "arrow.up.arrow.down")
        }
    }

    private func statusMenu(for po: PurchaseOrder) -> some View {
        Menu {
            ForEach(POStatus.allCases) { status in
                Button {
                    store.setStatus(status, for: po, by: authStore.currentUser)
                } label: {
                    Label(status.label, systemImage: status.systemImage)
                }
            }
        } label: {
            Label(po.status.label, systemImage: po.status.systemImage)
                .font(.caption2)
                .lineLimit(1)
                .minimumScaleFactor(0.8)
                .foregroundColor(po.status.color)
                // Fixed-width, leading-aligned block keeps the icon in the same
                // vertical column across rows so it doesn't shift as the label changes.
                .frame(width: 112, alignment: .leading)
        }
        .menuStyle(.borderlessButton)
    }
}

#Preview {
    HistoryView()
        .environmentObject(POStore())
        .environmentObject(AuthStore())
}
