import SwiftUI

struct HistoryView: View {
    @EnvironmentObject private var store: POStore

    var body: some View {
        NavigationStack {
            Group {
                if store.history.isEmpty && !store.isLoadingHistory {
                    VStack(spacing: 12) {
                        Image(systemName: "doc.text")
                            .font(.system(size: 40))
                            .foregroundColor(.secondary)
                        Text("No POs Yet")
                            .font(.headline)
                        Text("Purchase orders generated by you or your team will show up here.")
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 32)
                    }
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                } else {
                    List(store.history) { po in
                        NavigationLink(value: po) {
                            VStack(alignment: .leading, spacing: 4) {
                                HStack {
                                    Text(po.poNumber)
                                        .font(.system(.body, design: .monospaced))
                                        .bold()
                                    if po.isFulfilled {
                                        Spacer()
                                        Label("Fulfilled", systemImage: "checkmark.circle.fill")
                                            .font(.caption)
                                            .foregroundColor(.green)
                                    }
                                }
                                Text("\(po.customerName) · Job \(po.jobNumber)")
                                    .font(.subheadline)
                                    .foregroundColor(.secondary)
                                Text("By \(po.createdByName) · \(po.createdAt.formatted(date: .abbreviated, time: .shortened))")
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                            .padding(.vertical, 2)
                        }
                    }
                    .navigationDestination(for: PurchaseOrder.self) { po in
                        PODetailView(po: po)
                    }
                    .refreshable {
                        await store.loadHistory()
                    }
                }
            }
            .navigationTitle("History")
            .task {
                await store.loadHistory()
            }
        }
    }
}

#Preview {
    HistoryView()
        .environmentObject(POStore())
        .environmentObject(AuthStore())
}
