import SwiftUI

struct HistoryView: View {
    @EnvironmentObject private var store: POStore

    var body: some View {
        NavigationStack {
            Group {
                if store.history.isEmpty && !store.isLoadingHistory {
                    VStack(spacing: 12) {
                        Image(systemName: "doc.text")
                            .font(.system(size: 40))
                            .foregroundColor(.secondary)
                        Text("No POs Yet")
                            .font(.headline)
                        Text("Purchase orders generated by you or your team will show up here.")
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 32)
                    }
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                } else {
                    List(store.history) { po in
                        VStack(alignment: .leading, spacing: 4) {
                            Text(po.poNumber)
                                .font(.system(.body, design: .monospaced))
                                .bold()
                            Text("\(po.customerName) · Job \(po.jobNumber)")
                                .font(.subheadline)
                                .foregroundColor(.secondary)
                            Text(po.createdAt, format: .dateTime.month().day().hour().minute())
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                        .padding(.vertical, 2)
                    }
                    .refreshable {
                        await store.loadHistory()
                    }
                }
            }
            .navigationTitle("History")
            .task {
                await store.loadHistory()
            }
        }
    }
}

#Preview {
    HistoryView()
        .environmentObject(POStore())
}
